
[buildpack]
id = "com.starkandwayne.wp-cli"
name = "Wordpress CLI Buildpack"
version = "0.5.0"

[metadata]
include_files = ["bin/build","bin/detect","buildpack.toml"]
pre_package = "./scripts/build.sh"

[[stacks]]
id = "org.cloudfoundry.stacks.cflinuxfs3"

[[metadata.dependencies]]
id = "wp-cli"
name = "Wordpress CLI"
version = "2.2.0"
uri = "https://github.com/wp-cli/wp-cli/releases/download/v2.2.0/wp-cli-2.2.0.phar"
sha256 = "71ee8a2449f17bf8a6fd385872cbdc3cc263107f7767a3b55f6c6e2ef5920368"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
